// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package repository

import (
	"context"
	"database/sql"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses(
    title,
    amount,
    description
) VALUES (
    ?, ?, ?
) RETURNING id, title, amount, description, created_at, updated_at
`

type CreateExpenseParams struct {
	Title       sql.NullString `json:"title"`
	Amount      int64          `json:"amount"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense, arg.Title, arg.Amount, arg.Description)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpenseByID = `-- name: DeleteExpenseByID :exec
DELETE FROM expenses 
WHERE id = ?
`

func (q *Queries) DeleteExpenseByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseByID, id)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, title, amount, description, created_at, updated_at FROM expenses WHERE id = ?
`

func (q *Queries) GetExpenseByID(ctx context.Context, id int64) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenses = `-- name: GetExpenses :many
SELECT id, title, amount, description, created_at, updated_at FROM expenses
`

func (q *Queries) GetExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpenseByID = `-- name: UpdateExpenseByID :one
UPDATE expenses
SET title = ?, amount = ?, description = ?
WHERE id = ?
RETURNING id, title, amount, description, created_at, updated_at
`

type UpdateExpenseByIDParams struct {
	Title       sql.NullString `json:"title"`
	Amount      int64          `json:"amount"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateExpenseByID(ctx context.Context, arg UpdateExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, updateExpenseByID,
		arg.Title,
		arg.Amount,
		arg.Description,
		arg.ID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
