// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package repository

import (
	"context"
	"database/sql"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses(
    remark,
    amount
) VALUES (
    ?, ?
) RETURNING id, remark, amount, created_at
`

type CreateExpenseParams struct {
	Remark sql.NullString `json:"remark"`
	Amount int64          `json:"amount"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense, arg.Remark, arg.Amount)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.Remark,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpenseByID = `-- name: DeleteExpenseByID :exec
DELETE FROM expenses 
WHERE id = ?
`

func (q *Queries) DeleteExpenseByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpenseByID, id)
	return err
}

const getExpenses = `-- name: GetExpenses :many
SELECT id, remark, amount, created_at FROM expenses
`

func (q *Queries) GetExpenses(ctx context.Context) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, getExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.Remark,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
