// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Expense struct {
	ID        int64          `json:"id"`
	Remark    sql.NullString `json:"remark"`
	Amount    int64          `json:"amount"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
