// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"
)

type Expense struct {
	ID          int64          `json:"id"`
	Title       sql.NullString `json:"title"`
	Amount      int64          `json:"amount"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}
